import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { BarChart3, DollarSign, Hash, Activity } from 'lucide-react';
import { useStore } from '@/store';
export default function MetricsPage() {
    const llmPerformance = useStore((s) => s.llmPerformance);
    const agentMetrics = useStore((s) => s.agentMetrics);
    const tokenUsage = useStore((s) => s.tokenUsage);
    const fetchLLMPerformance = useStore((s) => s.fetchLLMPerformance);
    const fetchAgentMetrics = useStore((s) => s.fetchAgentMetrics);
    const fetchTokenMetrics = useStore((s) => s.fetchTokenMetrics);
    useEffect(() => {
        fetchLLMPerformance();
        fetchAgentMetrics();
        fetchTokenMetrics();
    }, [fetchLLMPerformance, fetchAgentMetrics, fetchTokenMetrics]);
    const tokenTimeSeries = tokenUsage?.timeSeries ?? [];
    const totalCost = agentMetrics.reduce((sum, m) => sum + m.totalCostUsd, 0);
    const totalTokens = agentMetrics.reduce((sum, m) => sum + m.totalTokensUsed, 0);
    const totalApiCalls = llmPerformance.reduce((sum, m) => sum + m.totalCalls, 0);
    return (_jsxs("div", { className: "p-6 space-y-6", children: [_jsxs("h1", { className: "text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2", children: [_jsx(BarChart3, { className: "w-6 h-6" }), "Metrics"] }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-4", children: [_jsxs("div", { className: "card flex items-center gap-4", children: [_jsx("div", { className: "p-3 rounded-lg text-green-600 bg-green-100 dark:bg-green-900/30 dark:text-green-400", children: _jsx(DollarSign, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Total Cost" }), _jsxs("p", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: ["$", totalCost.toFixed(4)] })] })] }), _jsxs("div", { className: "card flex items-center gap-4", children: [_jsx("div", { className: "p-3 rounded-lg text-blue-600 bg-blue-100 dark:bg-blue-900/30 dark:text-blue-400", children: _jsx(Hash, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Total Tokens" }), _jsx("p", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: totalTokens.toLocaleString() })] })] }), _jsxs("div", { className: "card flex items-center gap-4", children: [_jsx("div", { className: "p-3 rounded-lg text-purple-600 bg-purple-100 dark:bg-purple-900/30 dark:text-purple-400", children: _jsx(Activity, { className: "w-6 h-6" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: "Total API Calls" }), _jsx("p", { className: "text-2xl font-bold text-gray-900 dark:text-white", children: totalApiCalls.toLocaleString() })] })] })] }), _jsxs("div", { className: "card", children: [_jsx("h2", { className: "text-lg font-semibold text-gray-900 dark:text-white mb-4", children: "Token Usage Over Time" }), tokenTimeSeries.length > 0 ? (_jsx("div", { className: "h-64 flex items-end gap-1 px-4", children: tokenTimeSeries.slice(-30).map((point, i) => {
                            const maxTokens = Math.max(...tokenTimeSeries.map((p) => p.promptTokens + p.completionTokens), 1);
                            const height = ((point.promptTokens + point.completionTokens) / maxTokens) * 100;
                            return (_jsx("div", { className: "flex-1 flex flex-col items-center gap-0.5", title: `${new Date(point.timestamp).toLocaleDateString()}: ${point.promptTokens + point.completionTokens} tokens, $${point.costUsd.toFixed(4)}`, children: _jsx("div", { className: "w-full bg-primary-500 rounded-t opacity-80 hover:opacity-100 transition-opacity min-h-[2px]", style: { height: `${height}%` } }) }, i));
                        }) })) : (_jsx("div", { className: "h-64 flex items-center justify-center text-gray-400 dark:text-gray-500 border border-dashed border-gray-300 dark:border-gray-700 rounded-lg", children: _jsx("p", { children: "No usage data yet. Charts will appear once agents begin processing tasks." }) }))] }), _jsxs("div", { className: "card p-0 overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-gray-200 dark:border-gray-800", children: _jsx("h2", { className: "text-lg font-semibold text-gray-900 dark:text-white", children: "LLM Performance" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-200 dark:border-gray-800", children: [_jsx("th", { className: "text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Model" }), _jsx("th", { className: "text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Task Type" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Avg Duration" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Success Rate" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Total Calls" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Cost" })] }) }), _jsxs("tbody", { className: "divide-y divide-gray-100 dark:divide-gray-800", children: [llmPerformance.map((stat, i) => (_jsxs("tr", { className: "hover:bg-gray-50 dark:hover:bg-gray-800/50", children: [_jsx("td", { className: "px-4 py-3 text-sm font-medium text-gray-900 dark:text-white", children: stat.modelId }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: "badge-gray", children: stat.taskType }) }), _jsxs("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: [(stat.avgDurationMs / 1000).toFixed(2), "s"] }), _jsx("td", { className: "px-4 py-3 text-sm text-right", children: _jsxs("span", { className: stat.successRate >= 0.95
                                                            ? 'text-green-600 dark:text-green-400'
                                                            : stat.successRate >= 0.8
                                                                ? 'text-yellow-600 dark:text-yellow-400'
                                                                : 'text-red-600 dark:text-red-400', children: [(stat.successRate * 100).toFixed(1), "%"] }) }), _jsx("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: stat.totalCalls.toLocaleString() }), _jsxs("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: ["$", stat.totalCostUsd.toFixed(4)] })] }, i))), llmPerformance.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 6, className: "px-4 py-8 text-center text-gray-500 dark:text-gray-400", children: "No LLM performance data yet." }) }))] })] }) })] }), _jsxs("div", { className: "card p-0 overflow-hidden", children: [_jsx("div", { className: "px-4 py-3 border-b border-gray-200 dark:border-gray-800", children: _jsx("h2", { className: "text-lg font-semibold text-gray-900 dark:text-white", children: "Agent Metrics" }) }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-gray-200 dark:border-gray-800", children: [_jsx("th", { className: "text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Agent" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Tokens Used" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Cost" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Completed" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Failed" }), _jsx("th", { className: "text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider px-4 py-3", children: "Avg Response" })] }) }), _jsxs("tbody", { className: "divide-y divide-gray-100 dark:divide-gray-800", children: [agentMetrics.map((metric) => (_jsxs("tr", { className: "hover:bg-gray-50 dark:hover:bg-gray-800/50", children: [_jsx("td", { className: "px-4 py-3 text-sm font-medium text-gray-900 dark:text-white", children: metric.agentName }), _jsx("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: metric.totalTokensUsed.toLocaleString() }), _jsxs("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: ["$", metric.totalCostUsd.toFixed(4)] }), _jsx("td", { className: "px-4 py-3 text-sm text-right", children: _jsx("span", { className: "text-green-600 dark:text-green-400", children: metric.tasksCompleted }) }), _jsx("td", { className: "px-4 py-3 text-sm text-right", children: _jsx("span", { className: metric.tasksFailed > 0
                                                            ? 'text-red-600 dark:text-red-400'
                                                            : 'text-gray-400', children: metric.tasksFailed }) }), _jsxs("td", { className: "px-4 py-3 text-sm text-right text-gray-700 dark:text-gray-300", children: [(metric.avgResponseTimeMs / 1000).toFixed(2), "s"] })] }, metric.agentId))), agentMetrics.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 6, className: "px-4 py-8 text-center text-gray-500 dark:text-gray-400", children: "No agent metrics yet." }) }))] })] }) })] })] }));
}
